import numpy as np
A = np.array([[1,2], [3,4]])
print(A)
print(A[0][1])
print(A[0,1])
print(A[:,0])
print(A.T)
print(np.exp(A)) # can pass list np.exp(L)
B = np.array([[1,2,3],[4,5,6]])
print(B)
print(A.dot(B)) #inner dimensions must match
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.linalg.inv(A).dot(A))
print(np.trace(A))
print(np.diag(A)) #array([1, 4])
print(np.diag([1, 4])) # array([[1, 0],
                              #[0, 4]])
print(np.linalg.eig(A) )      
Lam, V = np.linalg.eig(A)
print(V[:,0] * Lam[0] == A @ V[:,0])
print(V[:,0] * Lam[0], A @ V[:,0])
print(np.allclose(V[:,0] * Lam[0], A @ V[:,0]))
print(np.allclose(V @ np.diag(Lam), A @ V))